#! /bin/sh
# Try to get version info from BIND server
PROGRAM=`basename $0`

if [ $# -ne 1 ]; then
   echo "get BIND name server version, need a target! "
   echo "Usage: $0 target"
   echo "example $0 10.1.2.3"
   exit 0
fi
TARGET=$1
# using dig
dig @$1 version.bind chaos txt
echo Authors BIND er i versionerne 9.1 og 9.2 - måske ...
dig @$1 authors.bind chaos txt
